application: gu-most-popular
version: 9
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /static
  static_dir: static
- url: /admin/.*
  script: admin.app
  login: admin
  secure: always
- url: /.*
  script: app.app

libraries:
- name: jinja2
  version: latest

builtins:
- deferred: on
- remote_api: on