application: gu-most-popular
version: 2
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /static
  static_dir: static
- url: /.*
  script: app.app

libraries:
- name: jinja2
  version: latest

builtins:
- deferred: on